ALTER TABLE public.alert_subscriptions
    ADD COLUMN IF NOT EXISTS only_send_on_changes BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS include_new_listings BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS include_price_drops BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS min_price_drop_usd DOUBLE PRECISION;
